version: "3.98"
services:
  web:
    build: .
    # TODO: This is not currently working. Getting: dwn-relay-web-1 exited with code 139
    command: node --experimental-specifier-resolution=node src
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "9000:9000"
